import PanelFillerCommon

specials["Spanish"]["Amazon_N"]["Level"] = ["N.11", "N.13", "N.18", "N.15", "N.19"]
specials["Spanish"]["Amazon_N"]["Attack"] = ["+85A", "+30A", "+60A", "+50A", "+300A"]
specials["Spanish"]["Amazon_N"]["Title"] = PanelFillerCommon.GetSpecialAmzTitle()
specials["Spanish"]["Dwarf_N"]["Level"] = ["N.11", "N.13", "N.17", "N.18", "N.19"]
specials["Spanish"]["Dwarf_N"]["Attack"] = ["+85A", "+25A", "+50A", "+40A", "+300A"]
specials["Spanish"]["Dwarf_N"]["Title"] = PanelFillerCommon.GetSpecialDwfTitle()
specials["Spanish"]["Barbarian_N"]["Level"] = ["N.11", "N.13", "N.13", "N.19"]
specials["Spanish"]["Barbarian_N"]["Attack"] = ["+85A", "+50A", "+30A", "+300A"]
specials["Spanish"]["Barbarian_N"]["Title"] = PanelFillerCommon.GetSpecialBarbTitle()
specials["Spanish"]["Knight_N"]["Level"] = ["N.11", "N.13", "N.18", "N.19"]
specials["Spanish"]["Knight_N"]["Attack"] = ["+85A", "+35A", "+45A", "+300A"]
specials["Spanish"]["Knight_N"]["Title"] = PanelFillerCommon.GetSpecialKgtTitle()
specials["Spanish"]["Amazon_N"]["Descr2"] = ["-1", "-1", "-1", "-1", "Ataque 2: LA IRA DE LA DIOSA"]
specials["Spanish"]["Amazon_N"]["Level2"] = ["-1", "-1", "-1", "-1", "N.20"]
specials["Spanish"]["Amazon_N"]["Descr"] = ["Ataque: ATAQUE VAMPÍRICO", "Ataque: FILO DEL NORTE", "Ataque: SOPLO MORTAL", "Ataque: SANGRE DE DRAGÓN", "Ataque: LA LUZ DE IANNA"]
specials["Spanish"]["Amazon_N"]["Defense"] = ["-35D", "-20D", "-50D", "-30D", "-5D"]
specials["Spanish"]["Dwarf_N"]["Descr2"] = ["-1", "-1", "-1", "-1", "Ataque 2: LA IRA DE LA DIOSA"]
specials["Spanish"]["Dwarf_N"]["Level2"] = ["-1", "-1", "-1", "-1", "N.20"]
specials["Spanish"]["Dwarf_N"]["Descr"] = ["Ataque: ATAQUE VAMPÍRICO", "Ataque: HALO DEL NORTE", "Ataque: ALIENTO DE SERPIENTE", "Ataque: HALO DE FUEGO", "Ataque: LA LUZ DE IANNA"]
specials["Spanish"]["Dwarf_N"]["Defense"] = ["-35D", "-60D", "-90D", "-100D", "-5D"]
specials["Spanish"]["Barbarian_N"]["Descr2"] = ["-1", "Ataque2: VOLCÁN", "-1", "Ataque 2: LA IRA DE LA DIOSA"]
specials["Spanish"]["Barbarian_N"]["Level2"] = ["-1", "N.18", "-1", "N.20"]
specials["Spanish"]["Barbarian_N"]["Descr"] = ["Ataque: ATAQUE VAMPÍRICO", "Ataque: TORMENTA DE FUEGO", "Ataque: MUERTE HELADA", "Ataque: LA LUZ DE IANNA"]
specials["Spanish"]["Barbarian_N"]["Defense"] = ["-35D", "-10D", "-10D", "-5D"]
specials["Spanish"]["Knight_N"]["Descr2"] = ["-1", "-1", "-1", "Ataque 2: LA IRA DE LA DIOSA"]
specials["Spanish"]["Knight_N"]["Level2"] = ["-1", "-1", "-1", "N.20"]
specials["Spanish"]["Knight_N"]["Descr"] = ["Ataque: ATAQUE VAMPÍRICO", "Arma: ESPADA DE FUEGO", "Ataque: AURORA BOREAL", "Ataque: LA LUZ DE IANNA"]
specials["Spanish"]["Knight_N"]["Defense"] = ["-35D", "-25D", "-15D", "-5D"]
